### ISSUE TITLE
Officially supported ruby version

### ISSUE THREAD

**Issue by MaxLap** [alekseyl/niceql#10]
Hello, i'm wondering what is the officially supported ruby version? Nothing is specified in the `.gemspec`, but there is a single use of `&.` in niceql.rb, which means it cannot support anything below `2.3.0`. 

Replacing the `&.` would probably be all that is needed for supporting lower versions. (In that case, adding the lower version to travis would help avoiding this mistake again).

**Comment by alekseyl** [comment]
Nope, not only &.  Do you actually need it for lower ruby versions?

I tried to lower it, but I also use tilda HEREDOC notation inside tests which also needs 2.3. 

Of course it's also doable, but does anybody really need 2.2 ruby?

You are free to make PR if you want to support lower versions.

**Comment by MaxLap** [comment]
Ah, alright, if there are more things then nevermind. It's only for when I run my tests on my gem which supports down to 2.1. I added a guard to the `require 'niceql'` for the `RUBY_VERSION`.

Thanks
