### ISSUE TITLE
Log output is not colorized

### ISSUE THREAD

**Issue by barrywoolgar** [alekseyl/niceql#2]
Hello, the prettifier is not colorizing ActiveRecord log output because `false` is being passed into the `Prettifier.prettify_sql` call in `AbstractAdapterLogPrettifier`.

I've tried this with passing `true` and it doesn't seem to break my Rails log, so I'm not sure if this is intentional or not.

Thanks

**Comment by alekseyl** [comment]
You are right, rails actually log with color, so it's may not be a problem to log with a color.

**Comment by barrywoolgar** [comment]
Hi @alekseyl I don't think this issue is resolved yet, please can we leave it open until there's an option to set the `colorize` option to true? I'll do a PR now to add an extra config option, unless you'd like to do it a different way? Thanks!

**Comment by alekseyl** [comment]
0.1.18 doesn't suit your needs?

**Comment by barrywoolgar** [comment]
Hi, the latest version I see here on master is 0.1.17

**Comment by alekseyl** [comment]
sorry, about it, must be got distracted and didn't make a push and build for a 0.1.18 version

**Comment by barrywoolgar** [comment]
No worries, thanks for updating this, works great!
