### ISSUE TITLE
Handling of comments and whitespace

### ISSUE THREAD

**Issue by codeasone** [alekseyl/niceql#5]
I'm considering using `niceql` to smarten up some of my migration files, but have encountered an issue with comment `--` and whitespace handling. 

Example input: 

```
--Insightful remark
SELECT * FROM Customers;

--Useless comment
SELECT * FROM Orders ;
``` 

Passing to `prettify_sql` currently produces: 

```
--Insightful remark SELECT * 
  FROM Customers; --Useless comment 
    SELECT * 
    FROM Orders ; 
``` 

It would be nice if whitespace and comments could be left unmodified.

**Comment by alekseyl** [comment]
OK will do in 0.1.20 version

**Comment by codeasone** [comment]
Awesome, thanks for your work on this so far.

**Comment by alekseyl** [comment]
check 0.1.20 plz

**Comment by codeasone** [comment]
Seeing: 

```
--Insightful remark SELECT * FROM Customers;
--Useless comment
  SELECT *
  FROM Orders;
```

**Comment by codeasone** [comment]
Would expect to see something beautified, but with whitespace and comments intact:

E.g. 

```
--Insightful remark
SELECT *
FROM Customers;

--Useless comment
SELECT *
FROM Orders;
```

**Comment by alekseyl** [comment]
Actually this is only when SQL starts with comment :(
other cases is fine and tested. 

will pach in 0.1.21

**Comment by alekseyl** [comment]
Hi. Fixed in 0.1.21 try it out.

**Comment by codeasone** [comment]
I'm seeing: 

```
--Insightful remark
SELECT *
  FROM Customers;
  --Useless comment
    SELECT *
    FROM Orders;
``` 

Thank you for your effort to assist so far.

**Comment by alekseyl** [comment]
this is different, you want to prettify two SQL queries at once. I didn;t implement such kind of stuff yet. I assume you make different issue. I'll deal with this in 0.1.22

**Comment by codeasone** [comment]
Okay, apologies for my misunderstanding. I'll open another issue relating to beautifying files containing multiple queries e.g. migration files.
